const MONEY_RE=/R\$\s*\d{1,3}(?:\.\d{3})*(?:,\d{2})?/gi;
const DATE_RE=/\b(?:\d{1,2}[/-]\d{1,2}[/-]\d{2,4}|\d{1,2}\s+de\s+[A-Za-zçãõáéíóú]+\s+de\s+\d{4})\b/gi;
const EMAIL_RE=/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/ig;
const PHONE_RE=/(?:\+55\s*)?(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4}[-.\s]?\d{4}/g;
const ACTION_HINTS=['comparecer','preencher','agendar','entregar','apresentar','enviar','protocolar','solicitar','acompanhar','retirar','pagar','assinar','cadastrar','acessar','anexar','inscrever'];
const DOCUMENT_HINTS=['documento','documentos','rg','cpf','comprovante','certidão','certidao','diploma','histórico','historico','currículo','curriculo','laudo','declaração','declaracao','registro profissional'];
const STAGE_HINTS=['prova objetiva','prova discursiva','redação','redacao','avaliação de títulos','avaliacao de titulos','teste de aptidão física','teste de aptidao fisica','taf','entrevista','heteroidentificação','heteroidentificacao','perícia médica','pericia medica','curso de formação','curso de formacao'];
const COTA_PATTERNS=[['PPP',/pretos?\s*,?\s*pardos?|pessoas negras|negros?\s+e\s+negras?|cota\s+ppp|reserva.*vagas.*pretos|pardos/gi],['PCD',/pessoa(?:s)?\s+com\s+defici[eê]ncia|pcd|defici[eê]ncia/gi],['INDÍGENAS',/ind[ií]genas?|povos?\s+ind[ií]genas?/gi],['QUILOMBOLAS',/quilombolas?/gi],['OUTRAS',/cota|reserva\s+de\s+vagas|a[cç]([ãa])o\s+afirmativa/gi]];
export function normalize(text=''){return String(text).replace(/\r\n?/g,'\n').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim();}
export function uniq(arr){return [...new Map(arr.filter(Boolean).map(v=>[v.toLowerCase(),v])).values()];}
function lines(text){return normalize(text).split('\n').map(x=>x.trim()).filter(Boolean);}
function sentences(text){return normalize(text).split(/(?<=[.!?])\s+|\n+/).map(x=>x.trim()).filter(Boolean);}
function matches(text,re){return [...text.matchAll(re)].map(m=>m[0].trim());}
function withHint(ls,hints){return uniq(ls.filter(line=>hints.some(h=>line.toLowerCase().includes(h))));}
export function extractCotas(text=''){const found=[];for(const [label,re] of COTA_PATTERNS)if(re.test(text))found.push(label);for(const [,re] of COTA_PATTERNS)re.lastIndex=0;return uniq(found);}
export function matchProfile(text,profile={},general={}){
 const lower=normalize(text).toLowerCase(), reasons=[],warnings=[],personalized=[],checklist=[];let score=50;
 if(profile.area){const q=profile.area.toLowerCase().trim();if(q&&lower.includes(q)){score+=15;reasons.push(`A expressão da sua área (“${profile.area}”) aparece no edital.`);}else warnings.push(`Não foi localizada uma menção direta à área “${profile.area}”. Verifique cargos e atribuições.`);}
 if(profile.education){const edu=profile.education.toLowerCase();const compatible=lower.includes(edu)||(/superior/.test(edu)&&/ensino superior|graduação|gradua[cç][aã]o/.test(lower))||(/médio/.test(edu)&&/ensino médio|nível médio/.test(lower));if(compatible){score+=15;reasons.push('Há sinais textuais de compatibilidade com a escolaridade informada.');}else warnings.push('A escolaridade informada não apareceu claramente compatível; confira os requisitos do cargo.');}
 if(profile.experience){const years=Number(profile.experience);if(Number.isFinite(years)&&years>0){if(/experi[eê]ncia|tempo de servi[cç]o/.test(lower)){score+=5;reasons.push('O edital menciona experiência/tempo de serviço; confira a quantidade exigida.');}else warnings.push('Sua experiência foi informada, mas não foi localizada exigência explícita no texto.');}}
 if(profile.modality){const label=profile.modality.toUpperCase();const matched=general.cotas.includes(label)||label==='PPP'&&/pretos?|pardos?|pessoas negras/.test(lower);if(matched){score+=10;reasons.push(`A modalidade ${label} aparece no edital.`);personalized.push(`Confira percentual reservado, critérios de autodeclaração e eventual heteroidentificação aplicáveis à modalidade ${label}.`);}else warnings.push(`Não foi detectada a modalidade ${label}. Procure também anexos e tabelas de vagas.`);}
 if(/designer|design/i.test((profile.area||'').toLowerCase())){if(/designer|design|ux|ui|produto/i.test(lower)){score+=5;personalized.push('Há referências relacionadas a design, UX/UI ou produto no texto.');}else warnings.push('Seu perfil é ligado a design, mas não foi encontrada função explicitamente relacionada.');}
 if(profile.state&&lower.includes(profile.state.toLowerCase()))reasons.push(`O estado/região informado (${profile.state}) aparece no texto.`);
 if(general.dates.length)checklist.push('Registrar todas as datas e criar lembretes.');if(general.fee.length)checklist.push('Conferir valor, prazo e condições de isenção da taxa.');if(general.documents.length)checklist.push('Separar documentos exigidos e verificar formato/validade.');if(general.stages.length)checklist.push('Montar preparação por etapa do certame.');if(general.cotas.length)checklist.push('Ler a seção de cotas/reserva de vagas e os anexos correspondentes.');checklist.push('Conferir o requisito exato do cargo desejado no edital oficial.');
 score=Math.max(0,Math.min(100,score));return {score,band:score>=80?'Alta':score>=60?'Média':'Baixa',reasons,warnings,personalized,checklist:uniq(checklist)};
}
export function extractContest(text,profile={}){
 const t=normalize(text),ls=lines(t),ss=sentences(t),salary=uniq(matches(t,MONEY_RE)).slice(0,12),dates=uniq(matches(t,DATE_RE)).slice(0,20),docs=withHint(ls,DOCUMENT_HINTS).slice(0,15),actions=withHint(ls,ACTION_HINTS).slice(0,15);
 const stages=uniq(ls.filter(line=>STAGE_HINTS.some(h=>line.toLowerCase().includes(h))||/etapa|fase|prova/i.test(line))).slice(0,15),contacts=uniq([...matches(t,EMAIL_RE),...matches(t,PHONE_RE)]).slice(0,10),cotas=extractCotas(t);
 const vacancies=uniq([...matches(t,/\b\d{1,5}\s+(?:vagas?|oportunidades?)\b/gi),...matches(t,/\b(?:ampla concorr[eê]ncia|reserva de vagas)\b[^.\n]*/gi)]).slice(0,12);
 const education=uniq(ls.filter(x=>/ensino (fundamental|m[eé]dio|t[eé]cnico|superior)|gradua[cç][aã]o|bacharelado|licenciatura|p[oó]s-gradua[cç][aã]o|mestrado|doutorado/i.test(x))).slice(0,12);
 const general={title:ls.find(x=>/(concurso|processo seletivo|edital)/i.test(x))||ls[0]||'Edital',overview:ss.slice(0,3).join(' '),salary,dates,vacancies,education,stages,documents:docs,actions,contacts,cotas,fee:uniq(matches(t,/taxa de inscri[cç][aã]o[^\n.]*/gi)).slice(0,5),sourceLength:t.length};
 return {general,profile:matchProfile(t,profile,general),disclaimer:'Use esta análise como guia de leitura. O edital oficial e os atos da banca organizadora prevalecem sobre qualquer extração automática.'};
}
export function analyzeText(raw=''){const t=normalize(raw),ls=lines(t),ss=sentences(t);return {title:ls[0]||'Serviço público',overview:ss.slice(0,3).join(' '),actions:withHint(ls,ACTION_HINTS).slice(0,12),documents:withHint(ls,DOCUMENT_HINTS).slice(0,12),deadlines:uniq([...matches(t,/\b\d+\s+dias?\s+(?:[uú]teis|corridos)\b/gi),...matches(t,DATE_RE)]).slice(0,12),costs:uniq(matches(t,/R\$\s*\d{1,3}(?:\.\d{3})*(?:,\d{2})?/gi)).slice(0,12),contacts:uniq([...matches(t,EMAIL_RE),...matches(t,PHONE_RE)]).slice(0,10),keyPoints:ss.filter(s=>/\b(?:deve|precisa|necess[aá]rio|obrigat[oó]rio|prazo|taxa|gratuito|agendamento)\b/i.test(s)).slice(0,7),disclaimer:'A análise é informativa e pode conter omissões. Confirme requisitos, prazos e valores na fonte oficial.'};}
